language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - sourceline: 'ppa:ubuntu-elisp/ppa'
    packages:
      - libclang-dev
      - emacs
      - emacs-snapshot
      - clang-tidy-4.0

compiler:
  - gcc
  - clang

env:
  - EMACS=emacs
  - EMACS=emacs-snapshot

script:
  - mkdir build
  - cd build
  - $EMACS --version
  - |
    cmake \
    -DEMACS_EXECUTABLE=$(which $EMACS) \
    -DIRONY_WARNINGS_AS_ERRORS=ON \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    ../server
  - make -k
  - make check
  - |
    ../server/run-clang-tidy.py \
    -clang-tidy-binary clang-tidy-4.0 \
    -clang-apply-replacements-binary clang-apply-replacements-4.0 \
    -p . \
    -warnings-as-errors='*' \
    -quiet
